// URL oficial encontrada no painel administrativo MOVE.
const MOVE_API_URL='https://script.google.com/macros/s/AKfycbxeBzi-dAxWo3uK34nbFHZjFO9-fBCBgyT_IP3Q7NpEhvcbV8F0apSwVat77hEEgyGKcA/exec';
const SESSION_KEY='move_client_portal_session_v1';
let CODE='',DATA=null,PAGE='home',FILTER='Todos';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>{if(!d)return'—';const x=new Date(String(d).length===10?d+'T12:00:00':d);return isNaN(x)?esc(d):x.toLocaleDateString('pt-BR')};
function driveFileId(item,url){if(item?.fileId)return String(item.fileId);const value=String(url||'');return value.match(/[?&]id=([^&]+)/)?.[1]||value.match(/\/d\/([^/]+)/)?.[1]||''}
document.querySelector('#today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();CODE=$('#accessCode').value.trim().toUpperCase();if(!CODE)return;await login()});
document.querySelector('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b)return;PAGE=b.dataset.page;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));render();toggleMenu(false)});
async function request(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error('Falha de conexão (HTTP '+r.status+').');const out=await r.json();if(!out.ok)throw new Error(out.error||'Não foi possível concluir.');return out}
async function login(){const btn=$('#loginBtn'),err=$('#loginError');err.textContent='';btn.disabled=true;btn.innerHTML='<span class="loader"></span>';try{const out=await request(MOVE_API_URL+'?action=clientLogin&code='+encodeURIComponent(CODE)+'&_='+Date.now());DATA=out.data;sessionStorage.setItem(SESSION_KEY,CODE);openApp()}catch(e){err.textContent=e.message}finally{btn.disabled=false;btn.textContent='Entrar'}}
async function loadPortal(notify=false){if(!CODE)return;$('#sync').textContent='Sincronizando...';try{const out=await request(MOVE_API_URL+'?action=clientLogin&code='+encodeURIComponent(CODE)+'&_='+Date.now());DATA=out.data;render();$('#sync').textContent='Atualizado agora';if(notify)toast('Painel atualizado.')}catch(e){$('#sync').textContent='Falha ao sincronizar';toast(e.message)}}
function openApp(){document.documentElement.style.setProperty('--client',DATA.company?.cor||'#fca311');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#sideCompany').textContent=DATA.company?.nome||'Cliente';render()}
function logout(){sessionStorage.removeItem(SESSION_KEY);CODE='';DATA=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden');$('#accessCode').value='';$('#accessCode').focus()}
function toggleMenu(force){const s=$('#sidebar');s.classList.toggle('open',typeof force==='boolean'?force:!s.classList.contains('open'))}
function render(){const titles={home:'Visão geral',planning:'Planejamentos',materials:'Materiais',campaigns:'Campanhas',calendar:'Calendário'};$('#pageTitle').textContent=titles[PAGE];$('#view').innerHTML=({home,planning,materials,campaigns,calendar})[PAGE]();}
function home(){const recent=[...(DATA.scheduled||[])].slice(-3).reverse(),weeks=[...(DATA.weeks||[])].sort((a,b)=>(a.numero||0)-(b.numero||0)).slice(0,3);return `<section class="hero"><span class="eyebrow">Olá, ${esc(DATA.company?.responsavel||DATA.company?.nome||'cliente')}</span><h1>Seu movimento está aqui.</h1><p>Veja logo no início uma prévia dos planejamentos e dos materiais que a MOVE preparou para sua marca.</p></section><div class="stats"><div class="stat"><small>Conteúdos planejados</small><b>${DATA.contents?.length||0}</b></div><div class="stat"><small>Semanas planejadas</small><b><em>${DATA.weeks?.length||0}</em></b></div><div class="stat"><small>Materiais disponíveis</small><b>${DATA.scheduled?.length||0}</b></div><div class="stat"><small>Campanhas</small><b>${DATA.campaigns?.length||0}</b></div></div><div class="section-head"><div><h3>Prévia do planejamento</h3><p>Um resumo das primeiras semanas planejadas para sua marca.</p></div><button class="btn btn-dark btn-sm" onclick="go('planning')">Ver planejamento completo</button></div><div class="grid">${weeks.map(homeWeekCard).join('')||empty('Planejamento em construção','Assim que a equipe publicar, a prévia aparecerá aqui.')}</div><div class="section-head"><div><h3>Prévia dos materiais</h3><p>Últimas artes, vídeos e legendas disponibilizados pela equipe.</p></div><button class="btn btn-dark btn-sm" onclick="go('materials')">Ver todos os materiais</button></div><div class="grid">${recent.map(mediaCard).join('')||empty('Nenhum material disponível','Os materiais publicados pela equipe aparecerão aqui.')}</div>`}
function homeWeekCard(w,i){const items=(DATA.contents||[]).filter(c=>String(c.weekId)===String(w.id));return `<article class="card"><div class="card-top"><span class="tag">Semana ${esc(w.numero||i+1)}</span><span class="tag neutral">${items.length} conteúdos</span></div><h4>${esc(w.objetivo||'Planejamento da semana')}</h4><p>${esc(w.linha||'Linha editorial em definição')}</p><div class="meta"><span>${fmt(w.inicio)} a ${fmt(w.fim)}</span></div>${items.slice(0,3).map(x=>`<div class="content-row" style="grid-template-columns:80px 1fr;padding:10px;margin-top:10px"><span class="tag neutral">${esc(x.tipo||'Conteúdo')}</span><div><b>${esc(x.titulo||'Sem título')}</b></div></div>`).join('')}<div class="actions"><button class="btn btn-light btn-sm" onclick="go('planning')">Abrir semana</button></div></article>`}
function planning(){const weeks=[...(DATA.weeks||[])].sort((a,b)=>(a.numero||0)-(b.numero||0));return `<div class="section-head"><div><h3>Planejamento estratégico</h3><p>Semanas, objetivos e conteúdos programados para sua marca.</p></div><span class="tag neutral">${weeks.length} semanas</span></div>${weeks.map((w,i)=>{const items=(DATA.contents||[]).filter(c=>String(c.weekId)===String(w.id));return `<article class="week ${i===0?'open':''}"><div class="week-head" onclick="this.parentElement.classList.toggle('open')"><div><span class="tag">Semana ${esc(w.numero||i+1)}</span><h4 style="margin-top:9px">${esc(w.objetivo||'Planejamento da semana')}</h4></div><b>＋</b></div><div class="week-body"><p style="color:var(--muted);font-size:12px"><b>Linha editorial:</b> ${esc(w.linha||'Em definição')} • ${fmt(w.inicio)} a ${fmt(w.fim)}</p>${items.map(x=>`<div class="content-row"><span class="tag neutral">${esc(x.tipo||'Conteúdo')}</span><div><b>${esc(x.titulo||'Sem título')}</b><p>${esc(x.descricao||x.ideia||'')}</p></div><button class="btn btn-light btn-sm" onclick="detail('${esc(x.id)}')">Abrir</button></div>`).join('')||'<div class="empty"><b>Conteúdos em preparação</b>A equipe ainda está montando esta semana.</div>'}</div></article>`}).join('')||empty('Planejamento em construção','Assim que a equipe publicar, ele aparecerá aqui.')}`}
function materials(){const list=[...(DATA.scheduled||[])].reverse();return `<div class="section-head"><div><h3>Materiais da sua marca</h3><p>Visualize artes, vídeos e legendas disponibilizados pela equipe MOVE.</p></div><span class="tag neutral">${list.length} materiais</span></div><div class="grid">${list.map(mediaCard).join('')||empty('Nenhum material disponível','Novos materiais aparecerão aqui automaticamente.')}</div>`}
function mediaCard(s){const ct=(DATA.contents||[]).find(x=>String(x.id)===String(s.contentId))||{},url=s.cloudUrl||'',mime=String(s.mime||''),fid=driveFileId(s,url),isVideo=mime.startsWith('video/'),drivePreview=fid?`https://drive.google.com/file/d/${encodeURIComponent(fid)}/preview`:'';let pv='';if(url&&fid)pv=`<iframe src="${drivePreview}" allow="autoplay; fullscreen" allowfullscreen loading="lazy" referrerpolicy="no-referrer" title="${isVideo?'Vídeo':'Imagem'} do material"></iframe>`;else if(url&&isVideo)pv=`<video src="${esc(url)}" controls playsinline preload="metadata"></video>`;else if(url)pv=`<img src="${esc(url)}" alt="Material" loading="lazy" referrerpolicy="no-referrer">`;else pv=`<div class="no-media">▧<br>Material sem prévia</div>`;return `<article class="card media-card"><div class="preview">${pv}</div><div class="media-info"><div class="card-top"><span class="tag">${esc(ct.tipo||'Material')}</span><span class="tag neutral">Visualização</span></div><h4>${esc(ct.titulo||s.fileName||'Material')}</h4><div class="meta"><span>${fmt(s.data)}</span><span>${esc(s.hora||'')}</span></div>${s.legenda?`<div class="caption">${esc(s.legenda).replace(/\n/g,'<br>')}</div>`:''}</div></article>`}
function campaigns(){return `<div class="section-head"><div><h3>Campanhas da sua marca</h3><p>Conceitos e ações estratégicas desenvolvidas pela MOVE.</p></div></div><div class="grid">${(DATA.campaigns||[]).map(c=>`<article class="card"><div class="card-top"><span class="tag">Campanha</span><span class="tag neutral">${esc(c.status||'Planejada')}</span></div><h4>${esc(c.nome||c.titulo||'Campanha')}</h4><p>${esc(c.ideia||c.descricao||c.objetivo||'')}</p><div class="meta"><span>${fmt(c.inicio||c.data)}</span><span>${esc(c.periodo||'')}</span></div><div class="actions"><button class="btn btn-dark btn-sm" onclick="campaignDetail('${esc(c.id)}')">Ver proposta</button></div></article>`).join('')||empty('Nenhuma campanha publicada','Quando houver uma campanha ativa, ela aparecerá aqui.')}</div>`}
function calendar(){const events=[...(DATA.agenda||[]),...(DATA.scheduled||[])].filter(x=>x.data);const now=new Date(),y=now.getFullYear(),m=now.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay();let cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=events.filter(x=>String(x.data).slice(0,10)===iso);cells+=`<div class="day"><small>${d}</small>${ev.map(x=>`<div class="event">${esc(x.titulo||x.nome||x.fileName||'Publicação')}</div>`).join('')}</div>`}return `<div class="section-head"><div><h3>${now.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h3><p>Datas de publicação, reuniões e entregas.</p></div></div><div class="calendar"><b>Dom</b><b>Seg</b><b>Ter</b><b>Qua</b><b>Qui</b><b>Sex</b><b>Sáb</b>${cells}</div>`}
function empty(a,b){return `<div class="empty"><b>${a}</b>${b}</div>`}function go(p){PAGE=p;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));render()}
function detail(id){const x=(DATA.contents||[]).find(v=>String(v.id)===String(id));if(!x)return;showModal(x.titulo||'Conteúdo',`<div class="detail">${esc(x.roteiro||x.descricao||x.ideia||'Sem detalhes adicionais.')}</div>`)}
function campaignDetail(id){const x=(DATA.campaigns||[]).find(v=>String(v.id)===String(id));if(!x)return;showModal(x.nome||x.titulo||'Campanha',`<div class="detail">${esc(x.ideia||x.descricao||'')}\n\nOBJETIVO\n${esc(x.objetivo||'')}\n\nEXECUÇÃO\n${esc(x.roteiro||x.execucao||x.observacoes||'')}</div>`)}
function showModal(title,body){$('#modal').innerHTML=`<div class="modal-box"><div class="modal-head"><h3>${esc(title)}</h3><button class="close" onclick="closeModal()">×</button></div>${body}</div>`;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.add('hidden'),3500)}
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
const saved=sessionStorage.getItem(SESSION_KEY);if(saved){CODE=saved;$('#accessCode').value=saved;login()}
