const ACCESS_PASSWORD='021MAX';
// DEPOIS DE IMPLANTAR O APPS SCRIPT, COLE A URL /exec ABAIXO:
const API_URL='https://script.google.com/macros/s/AKfycbxMvqLfsGUtAwO_GlA_5L7Mip7t8fx1blq7wy9DhqpQ5HJXjaNa3g67j6kpKc2mn1zR/exec';
const API_SECRET='021MAX';
const PAYEE={key:'57293143000156',name:'MARLLUS VINICIUS S ARARUJO',city:'URUCUI',bank:'MERCADO PAGO'};
let DB={clients:[],debts:[],transactions:[],settings:{}},PAGE='dashboard';
const $=s=>document.querySelector(s), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||Date.now()+'_'+Math.random().toString(16).slice(2), iso=d=>new Date(d).toISOString().slice(0,10), today=()=>iso(new Date());
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();if($('#password').value!==ACCESS_PASSWORD){$('#loginError').textContent='Senha incorreta.';return}sessionStorage.setItem('alvu_auth','1');openApp()};
document.querySelector('#menu').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;PAGE=b.dataset.page;document.querySelectorAll('#menu button').forEach(x=>x.classList.toggle('active',x===b));render();toggleMenu(false)};
function apiReady(){return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec$/i.test(API_URL)}
async function request(action,data={},method='GET'){if(!apiReady())throw new Error('Configure a URL do Apps Script.');if(method==='GET'){const q=new URLSearchParams({...data,action,secret:API_SECRET,_:Date.now()});const r=await fetch(API_URL+'?'+q);const o=await r.json();if(!o.ok)throw new Error(o.error);return o}const body=new URLSearchParams({...data,action,secret:API_SECRET});const r=await fetch(API_URL,{method:'POST',body});const o=await r.json();if(!o.ok)throw new Error(o.error);return o}
async function openApp(){$('#login').classList.add('hide');$('#shell').classList.remove('hide');await loadData()}
function logout(){sessionStorage.clear();location.reload()}function toggleMenu(v){$('#side').classList.toggle('open',typeof v==='boolean'?v:!$('#side').classList.contains('open'))}
async function loadData(notify=false){loading('Sincronizando financeiro...');try{if(apiReady()){DB=(await request('load')).data;localStorage.setItem('alvu_backup',JSON.stringify(DB));$('#syncText').textContent='Planilha sincronizada'}else{DB=JSON.parse(localStorage.getItem('alvu_backup')||'{"clients":[],"debts":[],"transactions":[],"settings":{}}');$('#syncText').textContent='Modo local â€” configure o Apps Script'}render();if(notify)toast('Dados atualizados.')}catch(e){DB=JSON.parse(localStorage.getItem('alvu_backup')||'{"clients":[],"debts":[],"transactions":[],"settings":{}}');$('#syncText').textContent='Backup local';render();toast(e.message)}finally{hideLoading()}}
async function save(){localStorage.setItem('alvu_backup',JSON.stringify(DB));render();if(apiReady()){try{await request('save',{payload:JSON.stringify(DB)},'POST');$('#syncText').textContent='Salvo na planilha'}catch(e){toast('Salvo localmente. '+e.message)}}}
function loading(t){$('#loadingText').textContent=t;$('#loading').classList.remove('hide')}function hideLoading(){$('#loading').classList.add('hide')}function toast(t){const x=$('#toast');x.textContent=t;x.classList.remove('hide');clearTimeout(x.t);x.t=setTimeout(()=>x.classList.add('hide'),3200)}
function status(c){if(c.status==='Pago')return{key:'paid',label:'Pago â€¢ prÃ³ximo '+br(c.nextDue)};const d=dayDiff(c.nextDue);return d<0?{key:'late',label:Math.abs(d)+' dia(s) atrasado'}:{key:'pending',label:d===0?'Vence hoje':d+' dia(s) para vencer'}}
function dayDiff(date){const a=new Date(today()+'T12:00:00'),b=new Date(String(date||today())+'T12:00:00');return Math.round((b-a)/86400000)}function br(d){return d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'â€”'}
function render(){const titles={dashboard:'Dashboard financeiro',clients:'Empresas e cobranÃ§as',debts:'Controle de dÃ­vidas',transactions:'MovimentaÃ§Ãµes',settings:'ConfiguraÃ§Ã£o'};$('#pageTitle').textContent=titles[PAGE];$('#view').innerHTML=({dashboard,clients,debts,transactions,settings})[PAGE]()}
function totals(){const income=DB.transactions.filter(x=>x.type==='Entrada').reduce((s,x)=>s+Number(x.value||0),0),outs=DB.transactions.filter(x=>x.type==='SaÃ­da'),expenses=outs.reduce((s,x)=>s+Number(x.value||0),0),companySpent=outs.filter(x=>(x.bucket||'Empresa')==='Empresa').reduce((s,x)=>s+Number(x.value||0),0),debtPaid=outs.filter(x=>x.bucket==='DÃ­vidas'||x.category==='DÃ­vidas').reduce((s,x)=>s+Number(x.value||0),0),proSpent=outs.filter(x=>x.bucket==='PrÃ³-labore').reduce((s,x)=>s+Number(x.value||0),0);return{income,expenses,debtPaid,company:income*.4-companySpent,debts:income*.4-debtPaid,prolabore:income*.2-proSpent,balance:income-expenses}}
function dashboard(){const t=totals(),expected=DB.clients.reduce((s,x)=>s+Number(x.monthly||0),0),late=DB.clients.filter(x=>status(x).key==='late').length;return `<section class="hero"><small>ALVUFINANCEIRO</small><h1>Seu dinheiro com direÃ§Ã£o.</h1><p>Cada entrada Ã© distribuÃ­da automaticamente: 40% empresa, 40% dÃ­vidas e 20% prÃ³-labore.</p></section><div class="stats"><div class="stat"><small>Recebido</small><b>${money(t.income)}</b></div><div class="stat"><small>Mensal previsto</small><b>${money(expected)}</b></div><div class="stat"><small>Saldo geral</small><b>${money(t.balance)}</b></div><div class="stat"><small>Clientes atrasados</small><b>${late}</b></div></div><div class="split"><section class="panel"><div class="panel-head"><h3>Quanto vocÃª pode gastar</h3><span class="badge paid">40 â€¢ 40 â€¢ 20</span></div><div class="allocation">${allocation('OperaÃ§Ã£o da empresa',t.company,'Saldo disponÃ­vel apÃ³s gastos da empresa','#1769e0')}${allocation('Pagamento de dÃ­vidas',t.debts,'Saldo disponÃ­vel da reserva de dÃ­vidas','#e98b15')}${allocation('PrÃ³-labore',t.prolabore,'Saldo disponÃ­vel para prÃ³-labore','#119767')}</div></section><section class="panel"><div class="panel-head"><h3>PrÃ³ximos vencimentos</h3></div>${DB.clients.slice().sort((a,b)=>String(a.nextDue).localeCompare(String(b.nextDue))).slice(0,6).map(c=>`<div style="padding:10px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between"><div><b style="font-size:11px">${esc(c.company)}</b><small style="display:block">${br(c.nextDue)}</small></div><span class="badge ${status(c).key}">${status(c).label}</span></div>`).join('')||'<p>Nenhuma empresa cadastrada.</p>'}</section></div>`}
function allocation(name,value,sub,color){return `<div class="allocation-row"><div><span>${name}</span><b>${money(value)}</b></div><small>${sub}</small><div class="bar"><i style="width:100%;background:${color}"></i></div></div>`}
function clients(){return `<div class="section-head"><div><h3>Contratos mensais</h3><p>Cadastre, cobre, envie e acompanhe cada empresa.</p></div><button class="btn primary" onclick="clientForm()">+ Nova empresa</button></div><div class="table-wrap"><table><thead><tr><th>Empresa</th><th>Contato</th><th>ServiÃ§o</th><th>Mensalidade</th><th>Vencimento</th><th>SituaÃ§Ã£o</th><th>AÃ§Ãµes</th></tr></thead><tbody>${DB.clients.map(c=>`<tr><td><b>${esc(c.company)}</b><br>${esc(c.responsible)}</td><td>${esc(c.phone)}<br>${esc(c.email)}</td><td>${esc(c.service)}</td><td><b>${money(c.monthly)}</b></td><td>${br(c.nextDue)}</td><td><span class="badge ${status(c).key}">${status(c).label}</span></td><td><div class="actions"><button class="btn light small" onclick="charge('${c.id}')">CobranÃ§a</button><button class="btn primary small" onclick="markPaid('${c.id}')">Pago</button><button class="btn light small" onclick="markPending('${c.id}')">Pendente</button><button class="btn light small" onclick="clientForm('${c.id}')">Editar</button><button class="btn danger small" onclick="removeClient('${c.id}')">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="7">Nenhuma empresa cadastrada.</td></tr>'}</tbody></table></div>`}
function clientForm(id=''){const c=DB.clients.find(x=>x.id===id)||{};modal(id?'Editar empresa':'Nova empresa',`<form id="form" class="form-grid"><div class="field"><label>Empresa *</label><input name="company" value="${esc(c.company||'')}" required></div><div class="field"><label>ResponsÃ¡vel *</label><input name="responsible" value="${esc(c.responsible||'')}" required></div><div class="field"><label>Telefone</label><input name="phone" value="${esc(c.phone||'')}"></div><div class="field"><label>E-mail *</label><input type="email" name="email" value="${esc(c.email||'')}" required></div><div class="field"><label>Mensalidade</label><input type="number" step="0.01" name="monthly" value="${c.monthly||''}" required></div><div class="field"><label>PrÃ³ximo vencimento</label><input type="date" name="nextDue" value="${c.nextDue||today()}" required></div><div class="field span"><label>ServiÃ§o / descriÃ§Ã£o</label><textarea name="service">${esc(c.service||'')}</textarea></div></form>`,async()=>{const q=Object.fromEntries(new FormData($('#form')));q.monthly=Number(q.monthly);if(!q.company||!q.email)return toast('Preencha os campos obrigatÃ³rios.');if(id)Object.assign(c,q);else DB.clients.push({...q,id:uid(),status:'Pendente',createdAt:new Date().toISOString()});closeModal();loading('Salvando empresa...');await save();hideLoading();toast('Empresa salva.')})}
function addMonth(date){const d=new Date(date+'T12:00:00'),day=d.getDate();d.setMonth(d.getMonth()+1,1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return iso(d)}
async function markPaid(id){const c=DB.clients.find(x=>x.id===id);if(!c)return;if(c.status==='Pago')return toast('Este ciclo jÃ¡ estÃ¡ marcado como pago.');if(!confirm('Registrar pagamento de '+c.company+'?'))return;loading('Registrando e dividindo pagamento...');DB.transactions.push({id:uid(),date:today(),type:'Entrada',category:'Mensalidade',description:'Mensalidade â€” '+c.company,value:Number(c.monthly),clientId:c.id});c.lastPaidAt=new Date().toISOString();c.lastPaidDue=c.nextDue;c.nextDue=addMonth(c.nextDue);c.status='Pago';await save();hideLoading();toast('Pago. Valor dividido em 40% / 40% / 20%.')}function markPending(id){const c=DB.clients.find(x=>x.id===id);if(!c)return;c.status='Pendente';save();toast('SituaÃ§Ã£o alterada para pendente.')}
function removeClient(id){if(!confirm('Excluir esta empresa?'))return;DB.clients=DB.clients.filter(x=>x.id!==id);save()}
function message(c){const d=dayDiff(c.nextDue),name=c.responsible||c.company,val=money(c.monthly),due=br(c.nextDue);if(c.status==='Pago')return `OlÃ¡, ${name}! Confirmamos o pagamento da mensalidade. Muito obrigado! O prÃ³ximo vencimento serÃ¡ em ${due}.`;if(d===0)return `OlÃ¡, ${name}! Passando para lembrar que a mensalidade de ${val}, referente aos serviÃ§os da ALVU, vence hoje (${due}). O pagamento pode ser realizado via Pix pela chave ${PAYEE.key}, em nome de ${PAYEE.name} â€” ${PAYEE.bank}. Caso jÃ¡ tenha pago, desconsidere. Obrigado!`;if(d===-1)return `OlÃ¡, ${name}! Identificamos que a mensalidade de ${val} venceu ontem (${due}) e ainda consta como pendente. VocÃª pode regularizar via Pix pela chave ${PAYEE.key}, em nome de ${PAYEE.name} â€” ${PAYEE.bank}. Se jÃ¡ realizou o pagamento, envie o comprovante para atualizarmos. Obrigado!`;if(d<0)return `OlÃ¡, ${name}! Tudo bem? A mensalidade de ${val}, vencida em ${due}, estÃ¡ hÃ¡ ${Math.abs(d)} dias em atraso. Para regularizar, utilize o Pix ${PAYEE.key}, em nome de ${PAYEE.name} â€” ${PAYEE.bank}. Se precisar alinhar a data, fale conosco. Caso jÃ¡ tenha pago, envie o comprovante. Obrigado!`;return `OlÃ¡, ${name}! Lembramos que a mensalidade de ${val} vence ${d===1?'amanhÃ£':'em '+d+' dias'}, no dia ${due}. Para facilitar, o pagamento pode ser feito via Pix ${PAYEE.key}, em nome de ${PAYEE.name} â€” ${PAYEE.bank}. Obrigado!`}
function tlv(id,value){value=String(value);return id+String(value.length).padStart(2,'0')+value}function clean(s,max){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9 $%*+\-./:]/gi,' ').toUpperCase().trim().slice(0,max)}function crc16(s){let crc=0xffff;for(let i=0;i<s.length;i++){crc^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=(crc&0x8000)?(crc<<1)^0x1021:crc<<1;crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,'0')}
function pixPayload(value,txid){const gui=tlv('00','BR.GOV.BCB.PIX'),key=tlv('01',PAYEE.key),mai=tlv('26',gui+key),base=tlv('00','01')+tlv('01','12')+mai+tlv('52','0000')+tlv('53','986')+tlv('54',Number(value).toFixed(2))+tlv('58','BR')+tlv('59',clean(PAYEE.name,25))+tlv('60',clean(PAYEE.city,15))+tlv('62',tlv('05',clean(txid||'ALVU',25)))+'6304';return base+crc16(base)}
function charge(id){const c=DB.clients.find(x=>x.id===id),pix=pixPayload(c.monthly,'ALVU'+c.id.slice(0,12)),qr='https://quickchart.io/qr?size=300&text='+encodeURIComponent(pix),msg=message(c);modal('CobranÃ§a â€” '+c.company,`<div class="pix-box"><img src="${qr}" alt="QR Code Pix"><h3>${money(c.monthly)}</h3><p>Vencimento: ${br(c.nextDue)}</p><div class="pix-code">${pix}</div><div class="actions" style="justify-content:center;margin-top:13px"><button class="btn light" onclick="copyText(${JSON.stringify(pix).replace(/"/g,'&quot;')})">Copiar Pix</button><button class="btn light" onclick="copyText(${JSON.stringify(msg).replace(/"/g,'&quot;')})">Copiar mensagem</button><button class="btn primary" onclick="downloadPdf('${c.id}')">Baixar PDF</button><button class="btn dark" onclick="sendEmail('${c.id}')">Enviar e-mail</button></div></div>`)}
async function copyText(t){await navigator.clipboard.writeText(t);toast('Copiado.')}
async function sendEmail(id){loading('Enviando cobranÃ§a por e-mail...');try{await request('sendCharge',{clientId:id},'POST');toast('E-mail enviado.')}catch(e){toast(e.message)}finally{hideLoading()}}
async function downloadPdf(id){loading('Gerando carnÃª em PDF...');try{const o=await request('paymentPdf',{clientId:id},'POST'),a=document.createElement('a');a.href='data:application/pdf;base64,'+o.base64;a.download=o.filename;a.click();toast('PDF gerado.')}catch(e){toast(e.message)}finally{hideLoading()}}
function debts(){const open=DB.debts.reduce((s,x)=>s+Math.max(0,Number(x.total)-Number(x.paid||0)),0);return `<div class="section-head"><div><h3>DÃ­vidas da agÃªncia</h3><p>Saldo devedor total: <b>${money(open)}</b></p></div><button class="btn primary" onclick="debtForm()">+ Nova dÃ­vida</button></div><div class="grid">${DB.debts.map(d=>{const left=Math.max(0,Number(d.total)-Number(d.paid||0)),pct=Math.min(100,Number(d.paid||0)/Number(d.total||1)*100);return `<article class="card"><span class="badge ${left?'pending':'paid'}">${left?'Em aberto':'Quitada'}</span><h4>${esc(d.creditor)}</h4><p>${esc(d.description)}</p><b>${money(left)} restantes</b><div class="bar"><i style="width:${pct}%"></i></div><p>Pago ${money(d.paid)} de ${money(d.total)} â€¢ vence ${br(d.due)}</p><div class="actions"><button class="btn primary small" onclick="payDebt('${d.id}')">Abater valor</button><button class="btn light small" onclick="debtForm('${d.id}')">Editar</button><button class="btn danger small" onclick="removeDebt('${d.id}')">Excluir</button></div></article>`}).join('')||'<div class="card">Nenhuma dÃ­vida cadastrada.</div>'}</div>`}
function debtForm(id=''){const d=DB.debts.find(x=>x.id===id)||{};modal(id?'Editar dÃ­vida':'Nova dÃ­vida',`<form id="form" class="form-grid"><div class="field"><label>Credor / dÃ­vida</label><input name="creditor" value="${esc(d.creditor||'')}" required></div><div class="field"><label>Valor total</label><input type="number" step="0.01" name="total" value="${d.total||''}" required></div><div class="field"><label>JÃ¡ pago</label><input type="number" step="0.01" name="paid" value="${d.paid||0}"></div><div class="field"><label>Vencimento</label><input type="date" name="due" value="${d.due||today()}"></div><div class="field span"><label>DescriÃ§Ã£o</label><textarea name="description">${esc(d.description||'')}</textarea></div></form>`,()=>{const q=Object.fromEntries(new FormData($('#form')));q.total=Number(q.total);q.paid=Number(q.paid);if(id)Object.assign(d,q);else DB.debts.push({...q,id:uid()});closeModal();save();toast('DÃ­vida salva.')})}
function payDebt(id){const d=DB.debts.find(x=>x.id===id);modal('Abater â€” '+d.creditor,`<form id="form"><div class="field"><label>Valor retirado da reserva de dÃ­vidas</label><input type="number" step="0.01" name="value" required></div></form>`,()=>{const v=Number(new FormData($('#form')).get('value'));if(v<=0)return;d.paid=Number(d.paid||0)+v;DB.transactions.push({id:uid(),date:today(),type:'SaÃ­da',category:'DÃ­vidas',bucket:'DÃ­vidas',description:'Pagamento â€” '+d.creditor,value:v,debtId:d.id});closeModal();save();toast('Abatimento registrado.')})}function removeDebt(id){if(confirm('Excluir dÃ­vida?')){DB.debts=DB.debts.filter(x=>x.id!==id);save()}}
function transactions(){return `<div class="section-head"><div><h3>HistÃ³rico financeiro</h3><p>Todas as entradas e saÃ­das.</p></div><button class="btn primary" onclick="transactionForm()">+ LanÃ§amento</button></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>DescriÃ§Ã£o</th><th>Valor</th><th></th></tr></thead><tbody>${DB.transactions.slice().reverse().map(x=>`<tr><td>${br(x.date)}</td><td><span class="badge ${x.type==='Entrada'?'paid':'late'}">${x.type}</span></td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td><b>${money(x.value)}</b></td><td><button class="btn danger small" onclick="removeTransaction('${x.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6">Sem movimentaÃ§Ãµes.</td></tr>'}</tbody></table></div>`}
function transactionForm(){modal('Novo lanÃ§amento',`<form id="form" class="form-grid"><div class="field"><label>Data</label><input type="date" name="date" value="${today()}"></div><div class="field"><label>Tipo</label><select name="type"><option>Entrada</option><option>SaÃ­da</option></select></div><div class="field"><label>Categoria</label><input name="category" placeholder="Equipamento, imposto, aluguel..."></div><div class="field"><label>Retirar de qual reserva?</label><select name="bucket"><option>Empresa</option><option>DÃ­vidas</option><option>PrÃ³-labore</option></select></div><div class="field"><label>Valor</label><input type="number" step="0.01" name="value" required></div><div class="field"><label>DescriÃ§Ã£o</label><input name="description"></div></form>`,()=>{const q=Object.fromEntries(new FormData($('#form')));q.value=Number(q.value);DB.transactions.push({...q,id:uid()});closeModal();save();toast('LanÃ§amento registrado.')})}function removeTransaction(id){if(confirm('Excluir lanÃ§amento?')){DB.transactions=DB.transactions.filter(x=>x.id!==id);save()}}
function settings(){return `<section class="panel"><div class="panel-head"><h3>Dados de recebimento</h3></div><div class="grid"><div class="card"><small>Chave Pix</small><h4>${PAYEE.key}</h4></div><div class="card"><small>DestinatÃ¡rio</small><h4>${PAYEE.name}</h4></div><div class="card"><small>InstituiÃ§Ã£o</small><h4>${PAYEE.bank}</h4></div></div><p style="color:var(--muted);font-size:11px">AutomaÃ§Ã£o: o Apps Script verifica diariamente os vencimentos, envia aviso quando faltam 2 dias e atualiza o status do novo ciclo.</p><button class="btn primary" onclick="testConnection()">Testar conexÃ£o</button></section>`}async function testConnection(){loading('Testando conexÃ£o...');try{await request('ping');toast('ConexÃ£o funcionando.')}catch(e){toast(e.message)}finally{hideLoading()}}
function modal(title,body,onSave){$('#modal').innerHTML=`<div class="modal-box"><div class="modal-head"><h3>${esc(title)}</h3><button class="x" onclick="closeModal()">Ã—</button></div>${body}${onSave?'<div style="text-align:right;margin-top:17px"><button id="modalSave" class="btn primary">Salvar</button></div>':''}</div>`;$('#modal').classList.remove('hide');if(onSave)$('#modalSave').onclick=onSave}function closeModal(){$('#modal').classList.add('hide')}
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};if(sessionStorage.getItem('alvu_auth'))openApp();
